version: "3.9"

networks:
  backend:
    name: backend
  database:
    name: database

volumes:
  wp:
    external: true
    name: wp
  db:
    external: true
    name: db
  

services:

  nginx:
    build: srcs/nginx
    restart: "always"
    ports:
      - "443:443"
      - "8443:8443"
    networks:
      - backend
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: srcs/wordpress
    restart: "always"
    env_file:
      - .env
    environment:
      - CURRENT_USER=$USER
    networks:
      - backend
      - database
    volumes:
      - wp:/var/www/html
    depends_on:
      - mysql

  mysql:
    build: srcs/mysql
    restart: "always"
    env_file:
      - .env
    networks:
      - database
    volumes:
      - db:/var/lib/mysql

#### BONUS
  ftp:
    build: srcs/ftp
    restart: "always"
    env_file:
      - .env
    tty: true
    ports:
      - "21:21"
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
  adminer:
    build: srcs/adminer
    restart: "always"
    networks:
      - database
    ports:
      - "8080:8080"
    depends_on:
      - mysql
